### ISSUE TITLE
Swift Sample 

### ISSUE THREAD

**Issue by Imtayaz** [MP0w/MPPlot#12]
Hi Alex, 

Do you have any sample code for Swift. 
I like to use this control in my project. 

Thanks in advance,
Imtee

**Comment by MP0w** [comment]
Sorry, the code is not production ready as it was done during an hackathon, I should probably rewrite it in swift

**Comment by girishsami** [comment]
I written swift code for this, please check below code.

  var graphView = MPGraphView()
 graphView = MPPlot.plot(with: .graph, frame: CGRect(x: 0, y: 0, width:cell.viewGraph.frame.size.width + 50, height: cell.viewGraph.frame.size.height)) as! MPGraphView
graphView.curved = true
            graphView.values = arrayCurrency as! [Any]
            graphView.fillColors = [UIColor(red: 197.0/255.0, green: 205.0/255.0, blue: 227.0/255.0, alpha: 1.0), UIColor(red: 197.0/255.0, green: 205.0/255.0, blue: 227.0/255.0, alpha: 1.0)]
            graphView.graphColor = UIColor(red: 94.0/255.0, green: 115.0/255.0, blue: 173.0/255.0, alpha: 1.0)
            cell.viewGraph.addSubview(graphView)
