### ISSUE TITLE
Compilation warning to fix

### ISSUE THREAD

**Issue by foffux** [MP0w/MPPlot#13]
Hello
Here you are what I can see in my console:

objc[174]: Class MPButton is implemented in both /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer and /private/var/mobile/Containers/Bundle/Application/BA13D00A-666B-4AB2-8045-60FBF73BB9A5/Chessboard.app/Chessboard. One of the two will be used. Which one is undefined.

Could you please rename your MPButton class to let this warning disappear, make a new pod version and release it?
This warning is not good at all but it is very simple to overcome.

Thank you.

**Comment by MP0w** [comment]
Oh, I did it but didn't close the issue. BTW the code is not production ready was done during an hackathon
